### ISSUE TITLE
64 or 32bit?

### ISSUE THREAD

**Issue by Nik-Lz** [diznq/sfwcl#15]
Hello. My understanding is that this doesn't work for 64bit patched Crysis? At least, that's what i did on my Windows 8.1 system and it doesn't work. is it 32bit exclusive? Thanks for the client anyway.

**Comment by diznq** [comment]
there are still some issues with x64 version, like random crashes during gameplay that are being fixed, but most of things should work... maybe you cantry compatibility mode and use Vista or 7, sometimes it can help fix the problems
